Bakim/ViewModels/EndTaskViewModel.cs
namespace Bakim.ViewModels
{
    public class EndTaskViewModel
    {
        public int TaskId { get; set; }
        public string Description { get; set; }
    }
}

Bakim/ViewModels/WorkTaskViewModel.cs
using Bakim.Entity;
using Bakim.Entity.Dto;
using Bakim.Entity.Views;

namespace Bakim.ViewModels
{
    public class WorkTaskViewModel
    {
        public List<WorkTask> WorkTasks { get; set; }
        public List<WorkTaskDto> Dtos { get; set; }
        public ApplicationUser User { get; set; }
        public List<ApplicationUser> AllUsers { get; set; }
        public WorkTask Task { get; set; }
        public EndTaskViewModel EndTaskViewModel { get; set; }
        public SectionDto SectionDto { get; set; }
        public SectionDtoViewModel SectionDtoViewModel { get; set; }

        public Section Section { get; set; }
        public SectionFault SectionFault { get; set; }
    }

    public class TaskViewModel
    {
        public List<atanankullanicilar>? atanankullanicilars { get; set; }
        public ApplicationUser User { get; set; }
        public WorkTask Task { get; set; }
        public List<ApplicationUser> AllUsers { get; set; }
        
        public List<WorkTask> WorkTasks { get; set; }
        public List<WorkTaskDto> Dtos { get; set; }
        public SectionDto SectionDto { get; set; }
        public SectionDtoViewModel SectionDtoViewModel { get; set; }
        public ProductionSection productionSection { get; set; }
        public Section Section { get; set; }
        public SectionFault SectionFault { get; set; }
        public SectionFaultCategory sectionFaultCategory { get; set; }
        public List<Varlik> varliks { get; set; }
        public Varlik varlik { get; set; }
        public List<Stock> stock { get; set; }

        
        public WorkTaskUser taskuser { get; set; }

        public List<Section> Sections { get; set; }
        public List<SectionFault> SectionFaults { get; set; }
        public List<WorkTaskUser> WorkTaskUsers { get; set; }
        public string Description { get; set; }

        public List<WorkTaskTransfer>? WorkTaskTransfers { get; set; }

        public List<ProductionSection> productionSections { get; set; }


         

    

        
    }
}

Bakim/Controllers/WorkTasksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Bakim.Business.Abstracts;
using Bakim.Dataaccess.Concrete.Contexts;
using Bakim.Entity;
using Bakim.Entity.Dto;
using Bakim.Entity.Views;
using Bakim.ViewModels;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Bakim.Controllers
{
     [Authorize]
    public class WorkTasksController : Controller
    {
        private readonly ICallService _callService;
        private readonly IWorkTaskService _workTaskService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWorkTaskTransferService _workTaskTransferService;
        private readonly IWorkTaskUserService _workTaskUserService;
        private readonly ISectionFaultService _sectionFaultService;
        private readonly ISectionService _sectionService;
        private readonly IFileService _fileService;
        private readonly IVarlikService _varlikService;
        private readonly IStockService _stockService;
        private readonly ITask_StockService _task_StockService;
        private readonly IProductionSectionService _productionSectionService;
        private readonly ISectionFaultCategoryService _sectionFaultCategoryService;
        public WorkTasksController(ICallService callService,IWorkTaskService workTaskService, UserManager<ApplicationUser> userManager, IWorkTaskTransferService workTaskTransferService, IWorkTaskUserService workTaskUserService, ISectionFaultService sectionFaultService, ISectionService sectionService, IFileService fileService,IVarlikService varlikService, IStockService stockService,ITask_StockService task_StockService,IProductionSectionService productionSectionService,ISectionFaultCategoryService sectionFaultCategoryService)
        {
            _callService = callService;
            _workTaskService = workTaskService;
            _userManager = userManager;
            _workTaskTransferService = workTaskTransferService;
            _workTaskUserService = workTaskUserService;
            _sectionFaultService = sectionFaultService;
            _sectionService = sectionService;
            _fileService = fileService;
            _varlikService = varlikService;
            _stockService = stockService;
            _task_StockService = task_StockService;
            _productionSectionService = productionSectionService;
            _sectionFaultCategoryService = sectionFaultCategoryService;
        }

        public async Task<IActionResult> WorkTasks(int id)
        {
            var tasks = _workTaskService.GetTasks().Data;
            List<WorkTaskDto> dtos = new();
            var sections = _sectionService.GetAll().Data;
            var task = _workTaskService.GetSingle(c=> c.TaskId == id).Data;
            var sectionFaults = _sectionFaultService.GetAll().Data;
            var users = _userManager.Users.ToList();
            SectionDto sectionDto = new SectionDto()
            {
                Sections = sections,
                SectionFaults = sectionFaults
                
            };

            // foreach(var item in tasks)
            // {
            //     item.Creator = await _userManager.FindByIdAsync(item.CreatorId);
            //     item.Receiver = await _userManager.FindByIdAsync(item.ReceiverId);
            //     item.Starter = await _userManager.FindByIdAsync(item.StarterId);

            //     List<WorkTaskTransfer> workTaskTransfers = _workTaskTransferService.GetAll(item.TaskId).Data;
            //     foreach(var worktransfer in workTaskTransfers)
            //     {
            //         worktransfer.TransferredUser = await _userManager.FindByIdAsync(worktransfer.TransferredUserId);
            //     }

            //      var dto = new WorkTaskDto()
            //     {
            //         WorkTask = item,
            //         WorkTaskTransfers = workTaskTransfers,
            //         WorkTaskUsers = _workTaskUserService.GetTaskUsers(item.TaskId).Data,
            //         SectionDto = sectionDto
            //     };
            //     dtos.Add(dto);
            //     foreach (var worktaskuser in dto.WorkTaskUsers)
            //     {
            //         worktaskuser.User = await _userManager.FindByIdAsync(worktaskuser.UserId);
            //     }
            // }
           
            TaskViewModel model = new()
            {
                AllUsers = users,
                SectionDto = sectionDto,
                Task = task,
                Dtos = dtos,
                WorkTasks = tasks,
                User = await _userManager.GetUserAsync(HttpContext.User)
            };
           

            return View(model);
        }
       

        [HttpGet]
        public async Task<object> GetIsEmri(DataSourceLoadOptions loadOptions)
        {

            var user = await _userManager.GetUserAsync(HttpContext.User);
            var tasks = _workTaskService.GetTasks().Data;
            var users = _userManager.Users.ToList();
            List<WorkTaskDto> dtos = new();
            var sections = _sectionService.GetAll().Data;
            var sectionFaults = _sectionFaultService.GetAll().Data;
            

            SectionDto sectionDto = new SectionDto()
            {
                Sections = sections,
                SectionFaults = sectionFaults 
            };

           var Contexts = new ApplicationDbContext();
             

            var result = new TaskViewModel()
            {

                User = user,
                WorkTasks = tasks,
                AllUsers = users,
                Dtos = dtos,
                SectionDto = sectionDto,
                atanankullanicilars = Contexts.atanankullanicilars.ToList()
            };
                
              return DataSourceLoader.Load(result.atanankullanicilars, loadOptions);
        }


        public object WorkTaskTable(DataSourceLoadOptions loadOptions)
        {
            using var context = new ApplicationDbContext();
            var query = context.atanankullanicilars.ToList();

            query = query.GroupBy(d => d.TaskId).Select(s=> new atanankullanicilar
            {
                TaskId = s.Key,
                TaskTitle = s.First().TaskTitle.Replace("ı", "i").Replace("İ", "I").Replace("Ğ", "G").Replace("ğ", "g").Replace("ş", "s").Replace("Ü", "U").Replace("Ş", "S").Replace("ç","c").Replace("Ç","C"),
                CreatedDate = s.First().CreatedDate,
                Durum = s.First().Durum,
                İlerleme = s.First().İlerleme,
                InProcess = s.First().InProcess,
                IsActive = s.First().IsActive,
                IsCompleted = s.First().IsCompleted,
                ReceiverId = s.First().ReceiverId,
                StarterId = s.First().StarterId,
                TaskDescription = s.First().TaskDescription?.Replace("ı", "i").Replace("İ", "I").Replace("Ğ", "G").Replace("ğ", "g").Replace("ş", "s").Replace("Ü", "U").Replace("Ş", "S").Replace("ç","c").Replace("Ç","C")
            }).ToList();
            return DataSourceLoader.Load(query,loadOptions);

        }

        public object Durum(DataSourceLoadOptions loadOptions)
        {

           using(var Contexts = new ApplicationDbContext())
           {
                var query = Contexts.atanankullanicilars.ToList();

                return DataSourceLoader.Load(query,loadOptions);
           }
        }



        public object usergetir(DataSourceLoadOptions loadOptions)
        {
            var users = _userManager.Users.ToList();

            return DataSourceLoader.Load(users, loadOptions);
        }
       
        
        // public async Task<IActionResult> IsEmirleri()
        // {
        //     var tasks = _workTaskService.GetTasks().Data;
        //     List<WorkTaskDto> dtos = new();
        //     var sections = _sectionService.GetAll().Data;
        //     var sectionFaults = _sectionFaultService.GetAll().Data;
        //     SectionDto sectionDto = new SectionDto()
        //     {
        //         Sections = sections,
        //         SectionFaults = sectionFaults
        //     };
            
        //     foreach (var item in tasks)
        //     {
        //         item.Creator = await _userManager.FindByIdAsync(item.CreatorId);
        //         item.Receiver = await _userManager.FindByIdAsync(item.ReceiverId);
        //         item.Starter = await _userManager.FindByIdAsync(item.StarterId);
 
        //         List<WorkTaskTransfer> workTaskTransfers = _workTaskTransferService.GetAll(item.TaskId).Data;
        //         foreach (var worktransfer in workTaskTransfers)
        //         {
        //             worktransfer.TransferredUser = await _userManager.FindByIdAsync(worktransfer.TransferredUserId);
        //         }
                
        //         var dto = new WorkTaskDto()
        //         {
        //             WorkTask = item,
        //             WorkTaskTransfers = workTaskTransfers,
        //             WorkTaskUsers = _workTaskUserService.GetTaskUsers(item.TaskId).Data,
        //             SectionDto = sectionDto
        //         };
        //         dtos.Add(dto);
        //         foreach (var worktaskuser in dto.WorkTaskUsers)
        //         {
        //             worktaskuser.User = await _userManager.FindByIdAsync(worktaskuser.UserId);
        //         }
        //     }
        //     var user = await _userManager.GetUserAsync(HttpContext.User);
        //     var users = _userManager.Users.ToList();
           
        //     var result = new WorkTaskViewModel() 
        //     { 
        //         User = user, 
        //         WorkTasks = tasks,
        //         AllUsers = users,

Bakim/Views/WorkTasks/AddTask.cshtml
@using Bakim.Entity.Views;

@model TaskViewModel

<div class="container">
    <div class="card card-flush shadow-sm">
        <form id="formid"  asp-controller="WorkTasks" asp-action="AddTask" enctype="multipart/form-data">
            <div class="card-header">
                <h3 class="card-title">Yeni İş Emri</h3>
            </div>

            <div class="card-body">   
                <div class="row">
                    <div class="col-md-6 mb-10">
                        <label for="exampleFormControlInput1" class="form-label">Resim</label>
                        <br>
                        <br>
                        <!--begin::Image input-->
                        <div class="image-input image-input-outline" data-kt-image-input="true"
                            style="background-image: url(/app/images/worktasks)">
                            <!--begin::Image preview wrapper-->
                            <div class="image-input-wrapper w-125px h-125px"
                                style="background-image: url()"></div>
                            <!--end::Image preview wrapper-->

                            <!--begin::Edit button-->
                            <label
                                class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                                data-kt-image-input-action="change" data-bs-toggle="tooltip" data-bs-dismiss="click"
                                title="Change avatar">
                                <i class="bi bi-pencil-fill fs-7"></i>

                                <!--begin::Inputs-->
                                <input type="file" name="file" accept=".png, .jpg, .jpeg" style="object-fit:cover;"/>
                                <input type="hidden" name="avatar_remove"/>
                                <!--end::Inputs-->
                            </label>
                            <!--end::Edit button-->

                            <!--begin::Cancel button-->
                            <span
                                class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                                data-kt-image-input-action="cancel" data-bs-toggle="tooltip" data-bs-dismiss="click"
                                title="Cancel avatar">
                                <i class="bi bi-x fs-2"></i>
                            </span>
                            <!--end::Cancel button-->

                            <!--begin::Remove button-->
                            <span
                                class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                                data-kt-image-input-action="remove" data-bs-toggle="tooltip" data-bs-dismiss="click"
                                title="Remove avatar">
                                <i class="bi bi-x fs-2"></i>
                            </span>
                            <!--end::Remove button-->
                        </div>
                        <!--end::Image input-->
                    </div>
                    <div class="col-md-6 row">

                         <div class="col-md-12">
                            <label for="exampleFormControlInput1" class="required form-label">Üretim Bölümü</label>
                            <select required onchange="uretimBirimiGetir($(this).val())" class="form-select form-select-sm form-select-solid" asp-for="Task.ProductionSectionId" data-control="select2"
                                data-placeholder="Üretim Bölümü Seçiniz">
                                <option value=""></option>  
                                @foreach (var item in Model.productionSections)
                                {
                                    <option value="@item.ProductionSectionId">@item.ProductionSectionName</option>
                                }
                                
                            </select>
                        </div>
                        <div class="col-md-12">
                            <label for="exampleFormControlInput1" class="required form-label">Birim</label>
                            <select id="sectionselectid" required class="form-select form-select-sm form-select-solid" name="Task.SectionId" data-control="select2"
                                data-placeholder="Birim Seçiniz">
                                <option value=""></option>
                            </select>
                        </div>
                    </div>

                    @if(User.IsInRole("Admin"))
                    { 
                        <div class="col-md-6 mb-6 mt-8">
                            <label for="exampleFormControlInput1" class="form-label">Atanacak Kullanıcı</label>
                            <select name="Task.ReceiverId" class="form-select form-select-sm form-select-solid col-12 hht-select-2" data-control="select2" 
                            data-placeholder="Kullanıcı Seçiniz" data-allow-clear="true">
                                <option value=""></option>
                                <option>Tümü</option>
                                @foreach (var item in Model.AllUsers)
                                {
                                    <option value="@item.Id">@item.UserName</option>
                                }
                            </select>
                        </div>
                    }
                    else{
                        <div class="col-md-6 mb-6 mt-8">
                            <label for="exampleFormControlInput1" class="form-label">Atanacak Kullanıcı</label>
                            <select name="Task.ReceiverId" class="form-select form-select-sm form-select-solid col-12 hht-select-2" data-control="select2" 
                            data-placeholder="Kullanıcı Seçiniz" data-allow-clear="true" disabled>
                                <option value=""></option>
                                <option>Tümü</option>
                                @foreach (var item in Model.AllUsers)
                                {
                                    <option value="@item.Id">@item.UserName</option>
                                }
                            </select>
                        </div>
                    }

                    <div class="col-md-6 mb-6 mt-8">
                        <label for="exampleFormControlInput1" class="form-label">Varlık</label>
                        <select asp-for="Task.VarlikId" class="form-select form-select-sm form-select-solid col-12 hht-select-2" data-control="select2" 
                        data-placeholder="Varlık Seçiniz" >
                            <option></option>
                            @foreach (var item in Model.varliks)
                            {
                                <option value="@item.VarlikId">@item.VarlikName</option>
                            } 
                        </select>
                    </div>  
                    <div class="col-md-6">
                        <label for="exampleFormControlInput1" class="form-label">Arıza Kategorisi</label>
                        <input type="text" class="form-control form-control-sm" id="faultcategory" disabled/>
                        <input type="hidden" name="FaultCategoryId"/>
                    </div> 
                    <div class="col-md-6">
                        <label for="exampleFormControlInput1" class="required form-label">Arıza</label>
                        <select required onchange="arizaKategorisiGetir($(this).val())" class="form-select form-select-sm form-select-solid"  asp-for="Task.SectionFaultId"
                            data-control="select2" data-placeholder="Arıza Seçiniz">
                            <option value=""></option>
                            @foreach(var item in Model.SectionDto.SectionFaults)
                            {
                                <option value="@item.SectionFaultId">@item.SectionFaultName</option>
                            }
                        </select>
                    </div>
                    <div class="d-flex flex-column mt-8 mb-8">
                        <label for="exampleFormControlTextarea1" class="form-label">Açıklama</label>
                        <textarea asp-for="Task.TaskDescription" class="form-control form-control-sm form-control-solid" rows="5"></textarea>
                    </div> 
                </div> 
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-end">
                    <div class="me-10 d-flex align-items-center">
                        <div class="form-check form-switch"> 
                            <input class="form-check-input" type="checkbox" asp-for="Task.Acil" id="flexCheckDefault"/>
                            <label class="form-check-label" for="flexCheckDefault">
                                Acil İş Emri
                            </label>
                        </div>  
                    </div>
                    <button id="submitbtn" type="button"  class="btn btn-primary">Oluştur</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

    @* $(document).ready(function() {
        $('#arizaSelectInput').on('change', function() {
            var arizaId = $(this).val();
            $.ajax({
            url: '/Ariza/GetKategoriByArizaId/' + arizaId,
            success: function(result) {
                $('#kategoriSelectInput').val(result.kategoriId);
            }
            });
        });
    }); *@

    function uretimBirimiGetir(value)
    {
        $("#sectionselectid").html("");
        $.ajax({
            url:"/WorkTasks/GetKategoriByAriza",
            method: "POST",
            data : {getiren: value},
            async: true,
            success:function(result){
                let option = $('<option></option>');
                $("#sectionselectid").append(option);
                for (let item of result)
                {
                    $('#sectionselectid').append("<option value=" + item.SectionId + ">" + item.SectionName + "</option>");
                }
            }
        })
    }

    function arizaKategorisiGetir(value)
    {
        $.ajax({
            url:"/WorkTasks/GetSectionFaultCategory",
            method: "POST",
            data: {getiren: value},
            async: true,
            success:function(result){
                for (let item of result)
                {
                    $('#faultcategory').val(item.FaultCategoryName);
                    $('[name="FaultCategoryId"]').val(item.FaultCategoryId);
                }
            }
        })
    }

    $(document).on('click','#submitbtn', function(e){
        e.preventDefault();
        if(checkInputs("formid"))
            $('#formid').submit();
    });

function checkInputs(formName) 
{
  const getform = "#" + formName;
  var result = true;
  $(getform)
    .find("input:required")
    .each(function () {
      if ($(this).val() === "") {
        result = false;
      }
    });
  $(getform)
    .find("select:required")
    .each(function () {
      if ($(this).val() === "") {
        result = false;
      }
    });
  $(getform)
    .find("textarea:required")
    .each(function () {
      if ($(this).val() === "") {
        result = false;
      }
    });
  if (result === false) {
    Swal.fire({
      text: "Zorunlu Alanları Doldurun.",
      icon: "error",
      timer: 1200,
      showConfirmButton: false,
    });
    return result;
  }
  return true;
}
</script>

Bakim/Views/WorkTasks/StartTask.cshtml
@using Bakim.Entity.Views;

@model TaskViewModel


<div class="container">
    <div class="card card-flush shadow-sm">
        <form asp-controller="WorkTasks" asp-action="StartTask" asp-route-id="@Model.Task.TaskId" method="POST">
            <div class="card-header">
                <h2 class="card-title">@Model.Task.TaskTitle</h2>
                <a asp-controller="WorkTasks" asp-action="TaskDetails" asp-route-id="@Model.Task.TaskId" class="btn btn-icon btn-warning mt-4">
                    <span class="svg-icon svg-icon-white svg-icon-2x"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"/><rect x="11" y="17" width="7" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"/>
                    <rect x="11" y="9" width="2" height="2" rx="1" transform="rotate(-90 11 9)" fill="currentColor"/></svg></span>
                </a>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-center">
                    <h3>İş Emrine Başlayın</h3>
                </div>  
                <div class="d-flex">
                    @if(Model.Dtos != null)
                    {
                        @foreach(var item in Model.Dtos.OrderByDescending(d=>d.WorkTask.CreatedDate))
                        {
                            @foreach(var dto in Model.Dtos.Where(d=>d.WorkTask.TaskId == item.WorkTask.TaskId))
                            {
                                if (dto.WorkTask.InProcess || dto.WorkTask.IsCompleted)
                                {
                                    <p class="text-primary">@(dto.WorkTask.Starter.UserName + " tarafından " + dto.WorkTask.ProcessStartedDate.ToString() + " tarihinde başlandı.")</p>
                                    if(dto.WorkTaskTransfers.Where(d=>d.WorkTaskId == dto.WorkTask.TaskId).ToList()!= null)
                                    {
                                        foreach (var transfer in dto.WorkTaskTransfers.Where(d=>d.WorkTaskId == dto.WorkTask.TaskId))
                                        {
                                            <p class="text-primary">@(transfer.TransferredDate.ToString() + " tarihinde " + transfer.TransferredUser.UserName + "'a transfer edildi.")</p>
                                        }
                                    @* if (dto.WorkTaskUsers.Count() > 1)
                                        {
                                            foreach(var involve in dto.WorkTaskUsers.Where(c=>c.WorkTaskId == dto.WorkTask.TaskId).OrderByDescending(c=>c.StartedDate))
                                            {
                                                if(involve.UserId != dto.WorkTask.StarterId)
                                                {
                                                    <p class="text-primary">@(involve.StartedDate + " tarihinde " + involve.User.UserName + " dahil oldu.")</p>
                                                } 
                                            }
                                        }*@
                                        
                                        if (dto.WorkTask.IsCompleted)
                                        {
                                            <p class="text-danger">@(dto.WorkTask.CompletedDate +" tarihinde tamamlandı.")</p>
                                        }
                                    }
                                }
                                else if(!dto.WorkTask.InProcess && !dto.WorkTask.IsCompleted)
                                {
                                    <p class="text-warning">Henüz başlanmadı.</p>
                                }
                                <a asp-action="TaskDetails" asp-route-taskId="@item.WorkTask.TaskId">Detayları Gör</a>
                            }
                        }
                    } 
                </div>
                <div class="row">
                    <div class="col-md-6 mb-6 mt-10">
                            <label for="exampleFormControlInput1" class="form-label">Üretim Bölümü</label>
                            <input type="text" class="form-control form-control-sm form-control-solid" value="@Model.productionSections.Where(c=>c.ProductionSectionId == Model.Task.ProductionSectionId).FirstOrDefault().ProductionSectionName" disabled/>
                        </div>
                        <div class="col-md-6 mb-6 mt-10">
                            <label for="exampleFormControlInput1" class="form-label">Üretim Birimi</label>
                            <input type="text" class="form-control form-control-sm form-control-solid" value="@Model.Sections.Where(c=>c.SectionId == Model.Task.SectionId).FirstOrDefault().SectionName" disabled/>
                        </div>
                    <div class="d-flex flex-column mt-10 mb-10">
                        <label for="exampleFormControlTextarea1" class="form-label">İş Açıklaması</label>
                        <textarea asp-for="Task.TaskDescription" class="form-control form-control-sm form-control-solid"  id="exampleFormControlTextarea1" rows="5" disabled></textarea>
                    </div>
                </div> 
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-end align-items-center">
                    <div class="me-10">
                        <div class="form-check form-switch"> 
                            <input class="form-check-input" type="checkbox" asp-for="Task.Acil" id="flexCheckDefault" disabled/>
                            <label class="form-check-label" for="flexCheckDefault">
                                Acil İş Emri
                            </label>
                        </div>
                    </div>  
                    @if (Model.Task.ReceiverId == null || Model.Task.ReceiverId != Model.User.Id || Model.Task.ReceiverId == Model.User.Id)
                    { 
                        <button type="submit" class="btn btn-primary">Başla</button>  
                    }
                </div>
            </div>
        </form>
    </div>
</div>
               
                        
                   