Bakim/ViewModels/VarlikViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bakim.Entity;

namespace Bakim.ViewModels
{
    public class VarlikViewModel
    {
        public List<Stock> Stoklar { get; set; }
        public List<Varlik> Varliklar { get; set; }

    }

    public class VarlikDetayViewModel
    {
        public VarlikGroup varlikGrubu { get; set; }
        public Varlik varlik { get; set; }
        public ProductionSection UretimBolumu { get; set; }
        public DetayGroup DetayGrubu { get; set; }

    }

    public class StokDetayViewModel
    {
        public StockGroup stokgrubu { get; set; }
        public Stock stok { get; set; }
        public ProductionSection uretimbolumu { get; set;}
        public StokKategori stokKategori { get; set; }
        public List<Stok_Firma> stokfirmalar { get; set; }
        public List<TedarikciFirma> firmalar { get; set; }
    }

    

   
}

Bakim/Controllers/VarlikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bakim.ViewModels;
using Bakim.Business.Abstracts;
using Microsoft.AspNetCore.Mvc;
using DevExtreme.AspNet.Mvc;
using DevExtreme.AspNet.Data;
using Bakim.Entity;
using Microsoft.AspNetCore.Authorization;

namespace Bakim.Controllers
{
    [Authorize]
    public class VarlikController : Controller
    {

        private readonly IDetayGroupService _detayGroupService;
        private readonly ITedarikciFirmaService _tedarikciFirmaService;
        private readonly IStockService _stockService;
        private readonly IStokKategoriService _stokKategoriService;
        private readonly IFileService _fileService;
        private readonly IVarlikGroupService _varlikGroupService;
        private readonly IProductionSectionService _productionSectionService;
        private readonly IVarlikService _varlikService;
        private readonly IStockGroupService _stockGroupService;
        private readonly IStok_FirmaService _stok_FirmaService;




        public VarlikController(IDetayGroupService detayGroupService, ITedarikciFirmaService tedarikciFirmaService, IStockService stockService, IStokKategoriService stokKategoriService, IFileService fileService, IVarlikGroupService varlikGroupService, IProductionSectionService productionSectionService, IVarlikService varlikService, IStockGroupService stockGroupService, IStok_FirmaService stok_FirmaService)
        {
            _detayGroupService = detayGroupService;
            _tedarikciFirmaService = tedarikciFirmaService;
            _stockService = stockService;
            _stokKategoriService = stokKategoriService;
            _fileService = fileService;
            _varlikGroupService = varlikGroupService;
            _productionSectionService = productionSectionService;
            _varlikService = varlikService;
            _stockGroupService = stockGroupService;
            _stok_FirmaService = stok_FirmaService;
        }

        public IActionResult VarlikListe(int filter = 2)
        {
             if(filter == 2 || filter == null)
            {
                ViewData["Name"] = "Tümünü Görüntülüyorsunuz";  
            }

            else if(filter == 1)
            {
               ViewData["Name"] = "Aktifleri Görüntülüyorsunuz";
            }
            else if(filter == 0)
            {
               ViewData["Name"] = "Pasifleri Görüntülüyorsunuz";
            }

            return View("VarlikListe",filter);
        }

        public IActionResult StokListe(int filter = 2)
        {

            if(filter == 2 || filter == null || filter == 0)
            {
                ViewData["Name"] = "Tümünü Görüntülüyorsunuz";  
            }

            else if(filter == 1)
            {
               ViewData["Name"] = "Aktifleri Görüntülüyorsunuz";
            }
            else if(filter == 10)
            {
               ViewData["Name"] = "Pasifleri Görüntülüyorsunuz";
            }

            return View("StokListe", filter);
        }

        public IActionResult StokDetay(int id)
        {
            var stok = _stockService.GetById(c=> c.StockId == id).Data;
            var model = new StokDetayViewModel()
            {
                stok = stok,
                
                stokgrubu = _stockGroupService.GetAll(c=> c.StockGroupId == stok.StockGroupId).Data.FirstOrDefault(),
                stokKategori = _stokKategoriService.GetAll(c=> c.StokKategoriId == stok.StokKategoriId).Data.FirstOrDefault(),
                uretimbolumu = _productionSectionService.GetAll().Data.FirstOrDefault(),
                stokfirmalar = _stok_FirmaService.GetAll(c=> c.StockId == id).Data,
                firmalar = new()
                

            };

            foreach(var item in model.stokfirmalar)
            {
                model.firmalar.Add(_tedarikciFirmaService.GetAll(c=>c.FirmaId == item.FirmaId).Data.First());
            }
                
            return View(model);
        }

        public IActionResult VarlikDetay(int id)
        {
            var varlik = _varlikService.GetById(c => c.VarlikId == id).Data;
            var model = new VarlikDetayViewModel()
            {
                varlik = varlik,
                DetayGrubu = _detayGroupService.GetAll(c => c.DetayGroupId == varlik.DetayGroupId).Data.FirstOrDefault(),
                UretimBolumu = _productionSectionService.GetAll().Data.FirstOrDefault(),
                varlikGrubu = _varlikGroupService.GetAll(c=>c.VarlikGroupId == varlik.VarlikGroupId).Data.FirstOrDefault()
            };
            return View(model);
        }

        public IActionResult EditVarlik(int? id)
        {
            var vm = new EditVarlikViewModel()
            {
                varlik = _varlikService.GetAll(c => c.VarlikId == id).Data.FirstOrDefault(),
                varlikkategorisi = _detayGroupService.GetAll().Data.FirstOrDefault(),
                Uretimbolumu = _productionSectionService.GetAll().Data,
                VarlikGruplari = _varlikGroupService.GetAll().Data,
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult EditVarlik(IFormFile file, Varlik varlik,int id)
        {
            var varliks = _varlikService.GetById(c => c.VarlikId == id);

            if(varlik == null)
            {
                return NotFound();
            }

            if(varlik != null)
            {

                varliks.Data.VarlikName = varlik.VarlikName;
                varliks.Data.VarlikCode =  varlik.VarlikCode;
                varliks.Data.ImagePath =  varlik.ImagePath;
                varliks.Data.VarlikGroupId =  varlik.VarlikGroupId;
                varliks.Data.DetayGroupId =  varlik.DetayGroupId;
                varliks.Data.CorporationId =  varlik.CorporationId;
                varliks.Data.ProductionSectionId =  varlik.ProductionSectionId;
                varliks.Data.InUse = varlik.InUse;
                varliks.Data.Pasif = varlik.Pasif;
            }


            if (varliks == null)
            {
                return NotFound();
            }
            _varlikService.Update(varliks.Data);
            _fileService.AddForVarlik(file, varliks.Data);

            return RedirectToAction("VarlikListe");
        }






        [HttpGet]
        public object VarlikListesi(DataSourceLoadOptions loadOptions,int? id = null)
        {
            List<Varlik> model = new List<Varlik>();
            if(id == 2 || id ==  null)
            {
            model = _varlikService.GetAll().Data.OrderByDescending(d=>d.UploadDate).ToList();
            }

            if(id == 1)
            {
            model = _varlikService.GetAll(c=> c.Pasif == false).Data.OrderByDescending(d=>d.UploadDate).ToList();
            }

            if(id == 0)
            {
            model = _varlikService.GetAll(c=> c.Pasif == true).Data.OrderByDescending(d=>d.UploadDate).ToList();
            }
            
            model.ForEach(c => c.DetayGroup = _detayGroupService.GetAll(k => k.DetayGroupId == c.DetayGroupId).Data.FirstOrDefault());
            model.ForEach(c => c.VarlikGroup = _varlikGroupService.GetAll(k => k.VarlikGroupId == c.VarlikGroupId).Data.FirstOrDefault());
            return DataSourceLoader.Load(model, loadOptions);
        }

        [HttpGet]
        public object DetayGruplari(DataSourceLoadOptions loadOptions)
        {
            var model = _detayGroupService.GetAll().Data;
            return DataSourceLoader.Load(model, loadOptions);

        }



        public IActionResult EditStock(int? id)
        {
            var model = new EditStockViewModel()
            {
               stok = _stockService.GetById(c=> c.StockId == id).Data,
               stokGruplari = _stockGroupService.GetAll().Data,
               stokKategori = _stokKategoriService.GetAll().Data.FirstOrDefault(),
               stokfirma = _stok_FirmaService.GetAll(c=> c.StockId == id).Data,
               firmalar = _tedarikciFirmaService.GetAll().Data
            };

            return View(model);

        }

        [HttpPost]
        public IActionResult EditStock(IFormFile file, Stock stock, int id,int[] FirmaIds)
        {

            var aratablo = _stok_FirmaService.GetAll(c=> c.StockId == id).Data;
            var stoklar = _stockService.GetById(c => c.StockId == id);

             foreach(var item in aratablo)
            {
                _stok_FirmaService.Delete(item);

            }

            foreach(var item in FirmaIds)
            {
                _stok_FirmaService.Add(new(){
                    FirmaId = item,
                    StockId = stoklar.Data.StockId
                    
                });
            }

            if(stock == null)
            {
                return NotFound();
            }
            else 
            {
                stoklar.Data.StockName = stock.StockName;
                stoklar.Data.StockCode = stock.StockCode;
                stoklar.Data.Price = stock.Price;
                stoklar.Data.ImagePath = stock.ImagePath;
                stoklar.Data.MinStock = stock.MinStock;
                stoklar.Data.MaxStock = stock.MaxStock;
                stoklar.Data.Barcode = stock.Barcode;
                stoklar.Data.StokKategoriId = stock.StokKategoriId;
                stoklar.Data.StockGroupId = stock.StockGroupId;
                stoklar.Data.StockAmount = stock.StockAmount;
                stoklar.Data.CorporationId = stock.CorporationId;
                stoklar.Data.Pasif = stock.Pasif;
            }

            _stockService.Update(stoklar.Data);
            _fileService.AddForStock(file, stoklar.Data);

            return RedirectToAction("StokListe");
        }


 
        [HttpGet]
        public object StokListesi(DataSourceLoadOptions loadOptions, int? id = 2)
        {
           
            var vm = new List<StokListe>();

            List<Stock> model = new List<Stock>();

Bakim/Views/Varlik/EditStock.cshtml
@using Bakim.ViewModels;

@model EditStockViewModel;


<div class="container">
    <div class="card card-flush shadow-sm">
        <form asp-controller="Varlik" asp-route-id="@Model.stok.StockId" asp-action="EditStock" method="post" enctype="multipart/form-data">
            <div class="card-header">
                <h3 class="card-title">@Model.stok.StockName ' i Düzenliyorsunuz</h3>
            </div>
            <div class="card-body py-5">
                <div class="row">
                    <div class="col-md-6 mb-10">
                        <div class="ms-8">
                            <label for="exampleFormControlInput1" class="form-label">Stok Resmi</label>
                            <br>
                            <br> 
                            <!--begin::Image input-->
                            <div class="image-input image-input-outline" data-kt-image-input="true">

                                @if(@Model.stok.ImagePath == null)
                                {
                                    <!--begin::Image preview wrapper-->
                                    <div class="image-input-wrapper w-150px h-150px"
                                        style="background-image: url(/app/images/HHT/Locha.jpeg)"></div>
                                    <!--end::Image preview wrapper-->
                                }
                                else
                                {
                                    <!--begin::Image preview wrapper-->
                                    <div class="image-input-wrapper w-150px h-150px"
                                        style="background-image: url(/app/images/stocks/@Model.stok.ImagePath)"></div>
                                    <!--end::Image preview wrapper-->
                                }    

                                <!--begin::Edit button-->
                                <label
                                    class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                                    data-kt-image-input-action="change" data-bs-toggle="tooltip" data-bs-dismiss="click"
                                    title="Change avatar">
                                    <i class="bi bi-pencil-fill fs-7"></i>

                                    <!--begin::Inputs-->
                                    <input type="file" name="file" accept=".png, .jpg, .jpeg" style="object-fit:cover;" />
                                    <input type="hidden" name="avatar_remove" />
                                    <!--end::Inputs-->
                                </label>
                                <!--end::Edit button-->

                                <!--begin::Cancel button-->
                                <span
                                    class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                                    data-kt-image-input-action="cancel" data-bs-toggle="tooltip" data-bs-dismiss="click"
                                    title="Cancel avatar">
                                    <i class="bi bi-x fs-2"></i>
                                </span>
                                <!--end::Cancel button-->

                                <!--begin::Remove button-->
                                <span
                                    class="btn btn-icon btn-circle btn-color-muted btn-active-color-primary w-25px h-25px bg-body shadow"
                                    data-kt-image-input-action="remove" data-bs-toggle="tooltip" data-bs-dismiss="click"
                                    title="Remove avatar">
                                    <i class="bi bi-x fs-2"></i>
                                </span>
                                <!--end::Remove button-->
                            </div>
                            <!--end::Image input-->
                        </div>
                    </div>

                    <div class="col-md-6 row">
                        <div class="col-md-12">
                            <label for="StockGroupId" class="required form-label">Stok Grubu</label>
                            <select id="stokgrup" onchange="kategorigetir($(this).val())"
                                class="form-select form-select-sm form-select-solid" data-control="select2" name="StockGroupId"
                                value="@Model.stok.StockGroupId" data-placeholder="Stok Grubu Seçiniz">
                                <option></option>
                                @foreach (var item in Model.stokGruplari)
                                {
                                    if(item.StockGroupId == Model.stok.StockGroupId)
                                    {
                                    <option selected value="@item.StockGroupId">@item.StockGroupName</option>
                                    }
                                    else
                                    {
                                        <option value="@item.StockGroupId">@item.StockGroupName</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="col-md-12">
                            <label for="StokKategoriId" class="required form-label">Stok Kategorisi</label>
                            <select id="skategoriselect" class="form-select form-select-sm form-select-solid"
                                data-control="select2" name="StokKategoriId" value="@Model.stok.StokKategoriId" data-placeholder="Kategori Seçiniz">
                                <option value=""></option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mb-10">
                            <label for="StockCode" class="required form-label">Stok Kodu</label>
                            <input type="text" class="form-control form-control-sm form-control-solid"
                                placeholder="Stok Kodu Yazınız" name="StockCode" value="@Model.stok.StockCode"/>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="mb-10">
                            <label for="StockName" class="required form-label">Stok Adı</label>
                            <input type="text" class="form-control form-control-sm form-control-solid"
                                placeholder="Stok Adı Yazınız" name="StockName" value="@Model.stok.StockName"/>
                        </div>
                    </div>
                     <div class="col-md-4">
                        <div class="mb-10">
                            <label for="Barcode" class="form-label">Barkod</label>
                            <input type="text" class="form-control form-control-sm form-control-solid"
                                placeholder="Barkod Yazınız" name="Barcode" value="@Model.stok.Barcode"/>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-10">
                            <label for="Price" class="required form-label">Fiyat</label>
                            <input type="number" class="form-control form-control-sm form-control-solid"
                                placeholder="Fiyat Yazınız" name="Price" value="@Model.stok.Price"/>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-10">
                            <label for="StockAmount" class="required form-label">Miktar</label>
                            <input type="number" class="form-control form-control-sm form-control-solid"
                                placeholder="Stok Miktarı Yazınız" name="StockAmount" value="@Model.stok.StockAmount"/>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-10">
                            <label for="MinStock" class="required form-label">Minimum Stok</label>
                            <input type="number" class="form-control form-control-sm form-control-solid"
                                placeholder="Min Stok Yazınız" name="MinStock" value="@Model.stok.MinStock" />
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-10">
                            <label for="MaxStock" class="required form-label">Maksimum Stok</label>
                            <input type="number" class="form-control form-control-sm form-control-solid"
                                placeholder="Max Stok Yazınız" name="MaxStock" value="@Model.stok.MaxStock" />
                        </div>
                    </div>
                    <div class="col-md-8">
                        <label for="FirmaId" class="form-label">Tedarikçi Firma</label>
                        <select class="form-select form-select-sm form-select-solid" data-control="select2" multiple name="FirmaIds[]"
                            data-placeholder="Tedarikçi Firma Seçiniz">
                            @foreach (var item in Model.firmalar)
                            {
                                if(Model.stokfirma.Where(c=>c.FirmaId == item.FirmaId).Any())
                                {                                
                                    <option selected value="@item.FirmaId">@item.FirmaAdi</option>
                                } 
                                else
                                {                           
                                    <option value="@item.FirmaId">@item.FirmaAdi</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="col-md-4 mt-10 d-flex align-items-center justify-content-center">
                           <div class="form-check form-switch">
                                <input asp-for="@Model.stok.Pasif" name="Pasif" class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
                                <label class="form-check-label" for="flexSwitchCheckDefault">Pasif</label>
                            </div>
                    </div>
                </div>
            </div> 
            <div class="card-footer">
                <button type="submit" class="btn btn-primary mb-4" style="float: right;">Kaydet</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function()
    {
        $('#stokgrup').trigger("change");
    })
    function kategorigetir(value) {
        $('#skategoriselect').html("");
        $.ajax({
            url: "/Describing/KategoriGetir",
            method: "GET",  // istek türü (GET veya POST)
            data: { getiren: value },  // gönderilecek veriler
            async: true,
            success: function (result) {
                let option = $('<option></option>');
                $('#skategoriselect').append(option);
                console.log(result);
                for (let item of result) {
                    if(item.StokKategoriId == @Model.stok.StokKategoriId)
                    {
                        $('#skategoriselect').append("<option selected value=" + item.StokKategoriId + ">" + item.StokKategoriName + "</option>");
                    }
                    else
                    {
                        $('#skategoriselect').append("<option value=" + item.StokKategoriId + ">" + item.StokKategoriName + "</option>");

                    }
                }
            }
        });
    }
</script>

Bakim/Views/Varlik/StokListe.cshtml
@model int;

<div class="container">
    <div class="d-flex justify-content-between mb-4">
        <div class="d-flex align-items-center">
            <h4>- @ViewData["Name"]</h4>
        </div>
        <div class="align-items-center align-items-middle">
           <a asp-controller="Describing" asp-action="Stock" class="btn btn-success me-10">Stok Ekle</a>
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Filtreler
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" asp-controller="Varlik" asp-action="StokListe" asp-route-filter="2">Tümü</a></li>
                    <li><a class="dropdown-item" asp-controller="Varlik" asp-action="StokListe" asp-route-filter="1">Aktifler</a></li>
                    <li><a class="dropdown-item" asp-controller="Varlik" asp-action="StokListe" asp-route-filter="10">Pasifler</a></li>
                </ul>
            </div>
        </div>        
    </div>
   
    <div class="card border-0 card-p">
        @(Html.DevExtreme().DataGrid<StokListe>()
        .ID("stoklistesi")
        .ShowBorders(true)
        .DataSource(d => d.Mvc().LoadAction("Stoklistesi").Controller("Varlik").LoadParams(new{id = Model})
        )
        .FilterRow(filterRow => filterRow
        .Visible(true)
        .ApplyFilter(GridApplyFilterMode.Auto)
        )
        .Height("100%")
        .SearchPanel(searchPanel => searchPanel.Visible(true).Width(300))
        .Paging(paging => paging.PageSize(10))
        .Pager(p=>
        p.AllowedPageSizes(new JS("[5, 10, 20]"))
        .ShowNavigationButtons(true)
        .ShowPageSizeSelector(true)
        .Visible(true)
        .ShowNavigationButtons(true)
        .ShowInfo(true)
        .DisplayMode(GridPagerDisplayMode.Full)
        )
        .KeyExpr("StockId")
        .Columns(columns => {
            @* columns.AddFor(m => m.ImagePath).CellTemplate(@<text>
                <div>
                <img style="max-width:100%; height:auto;" src="/app/images/varliks/<%- data.ImagePath %>" alt="" />
                </div>
                </text>).Caption("Stok Resmi"); *@

        columns.AddFor(m => m.stock.stokGrubu.StockGroupName).Caption("Stok Grubu");

        columns.AddFor(m => m.stock.stokKategori.StokKategoriName).Caption("Stok Kategorisi");

        columns.AddFor(m => m.stock.StockName).Caption("Stok Adı");

        columns.AddFor(m => m.stock.StockCode).Caption("Stok Kodu");
        
        columns.AddFor(m=> m.tedarikciFirmalar).CellTemplate(new JS("tedarikfirmalar")).Caption("Tedarikçiler");

        columns.AddFor(m=>m.stock.UploadDate).DataType(GridColumnDataType.DateTime).Format("dd-MM-yyyy HH:mm").Caption("Eklenme Tarihi").SortOrder(SortOrder.Desc);
 
        columns.AddFor(m=>m.stock.StockId).Alignment(HorizontalAlignment.Center).AllowEditing(false).AllowFiltering(false).AllowSearch(false).CellTemplate(new JS("editbutton")).Caption("").Alignment(HorizontalAlignment.Center).Width(90);

        columns.AddFor(m=>m.stock.StockId).Alignment(HorizontalAlignment.Center).AllowEditing(false).AllowFiltering(false).AllowSearch(false).CellTemplate(new JS("detayButon")).Caption("Detay").Alignment(HorizontalAlignment.Center).Width(90); 

        })
        )


    </div>
    

   

</div>
<script>

    var permission = '@User.IsInRole("Admin")';

    function editbutton(container, options) { 

        if(permission != "True")
        {
            return;
        }

       
        $('<a href="/varlik/editstock?id=' + options.data.stock.StockId + '" class="btn btn-icon btn-primary"><!--begin::Svg Icon | path:/var/www/preview.keenthemes.com/kt-products/docs/metronic/html/releases/2022-12-26-231111/core/html/src/media/icons/duotune/art/art005.svg-->\
        <span class="svg-icon svg-icon-muted svg-icon- 2x"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path opacity="0.3" d="M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.08251.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.99626.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.0639920.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.79342.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z" fill="currentColor"/><path d="M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.378921.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.69618.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z" fill="currentColor"/></svg></span></a>').appendTo(container);
    }


    function detayButon(container, options) {      
        $('<a href="/varlik/StokDetay?id=' + options.data.stock.StockId + '" class="btn btn-icon btn-warning"><!--begin::Svg Icon | path:/var/www/preview.keenthemes.com/kt-products/docs/metronic/html/releases/2022-12-26-231111/core/html/src/media/icons/duotune/general/gen045.svg-->\
        <span class="svg-icon svg-icon-muted svg-icon-2hx"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor"/><rect x="11" y="17" width="7" height="2" rx="1" transform="rotate(-90 11 17)" fill="currentColor"/><rect x="11" y="9" width="2" height="2" rx="1" transform="rotate(-90 11 9)" fill="currentColor"/></svg></span> </a>').appendTo(container);
    }
    function tedarikfirmalar(container, options){
        if(options.data.tedarikciFirmalar.length > 0){
            if(options.data.tedarikciFirmalar.length == 1){
                 $('<span>'+options.data.tedarikciFirmalar[0].FirmaAdi + '</span>').appendTo(container);
            }
            else{
                $('<span>'+options.data.tedarikciFirmalar[0].FirmaAdi + ' +'+(options.data.tedarikciFirmalar.length-1)+' tane daha</span>').appendTo(container);
            }
        }
        else {
            $('<span>""</span>').appendTo(container);
        }
    }
</script>